/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MagnetsRouteImport } from './routes/magnets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as PracticeMediumRouteImport } from './routes/practice.medium'
import { Route as PracticeLowRouteImport } from './routes/practice.low'
import { Route as PracticeHighRouteImport } from './routes/practice.high'

const MagnetsRoute = MagnetsRouteImport.update({
  id: '/magnets',
  path: '/magnets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeMediumRoute = PracticeMediumRouteImport.update({
  id: '/practice/medium',
  path: '/practice/medium',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeLowRoute = PracticeLowRouteImport.update({
  id: '/practice/low',
  path: '/practice/low',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeHighRoute = PracticeHighRouteImport.update({
  id: '/practice/high',
  path: '/practice/high',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/magnets': typeof MagnetsRoute
  '/practice/high': typeof PracticeHighRoute
  '/practice/low': typeof PracticeLowRoute
  '/practice/medium': typeof PracticeMediumRoute
  '/practice/': typeof PracticeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/magnets': typeof MagnetsRoute
  '/practice/high': typeof PracticeHighRoute
  '/practice/low': typeof PracticeLowRoute
  '/practice/medium': typeof PracticeMediumRoute
  '/practice': typeof PracticeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/magnets': typeof MagnetsRoute
  '/practice/high': typeof PracticeHighRoute
  '/practice/low': typeof PracticeLowRoute
  '/practice/medium': typeof PracticeMediumRoute
  '/practice/': typeof PracticeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/magnets'
    | '/practice/high'
    | '/practice/low'
    | '/practice/medium'
    | '/practice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/magnets'
    | '/practice/high'
    | '/practice/low'
    | '/practice/medium'
    | '/practice'
  id:
    | '__root__'
    | '/'
    | '/magnets'
    | '/practice/high'
    | '/practice/low'
    | '/practice/medium'
    | '/practice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MagnetsRoute: typeof MagnetsRoute
  PracticeHighRoute: typeof PracticeHighRoute
  PracticeLowRoute: typeof PracticeLowRoute
  PracticeMediumRoute: typeof PracticeMediumRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/magnets': {
      id: '/magnets'
      path: '/magnets'
      fullPath: '/magnets'
      preLoaderRoute: typeof MagnetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/medium': {
      id: '/practice/medium'
      path: '/practice/medium'
      fullPath: '/practice/medium'
      preLoaderRoute: typeof PracticeMediumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/low': {
      id: '/practice/low'
      path: '/practice/low'
      fullPath: '/practice/low'
      preLoaderRoute: typeof PracticeLowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/high': {
      id: '/practice/high'
      path: '/practice/high'
      fullPath: '/practice/high'
      preLoaderRoute: typeof PracticeHighRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MagnetsRoute: MagnetsRoute,
  PracticeHighRoute: PracticeHighRoute,
  PracticeLowRoute: PracticeLowRoute,
  PracticeMediumRoute: PracticeMediumRoute,
  PracticeIndexRoute: PracticeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
